//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2016-01-12 18:04:04 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Entity.Infrastructure;
using ITOrm.EF.Models.Specification;
using ITOrm.EF.Models.Helper;
using ITOrm.EF.Models.Context;
namespace ITOrm.EF.Models.Host
{
    /// <summary>
    /// 表: 备注
    /// </summary>
    [Serializable]
    public class SystemIcon : BaseEntityAction<SystemIcon>
    {
        #region Entity Field
                
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public int ID { get; set; }
                        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(50)]
        public string Name { get; set; }
                        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(50)]
        public string Groups { get; set; }
                        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(50)]
        public string ParentGroups { get; set; }
        #endregion

        #region Data

        /// <summary>
        /// 数据库名称
        /// </summary>
        public override string DataName { get { return "ITOrmdb"; } }

        /// <summary>
        /// 表名称
        /// </summary>
        public override string DataTableName { get { return "SystemIcon"; } }

        #endregion

        #region Hyperemia
        public override BaseEntity Clone()
        {
            return this as BaseEntity;
        }
        #endregion

        #region ==========查询单一实体

        /// <summary>
        /// 根据lamda表达式获取单一实体,如果没有找到则返回null
        /// </summary>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <returns>SystemIcon实体对象</returns>
        public static SystemIcon Single(ISpecification<SystemIcon> specification)
        {
            SystemIcon entity = new SystemIcon();
            if (specification != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        entity = db.BaseDbSet.FirstOrDefault(specification.Predicate);
					}
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return entity;
        }

        /// <summary>
        /// 根据lamda表达式获取单一实体,如果没有找到则返回null
        /// </summary>
        /// <param name="predicate">表达式</param>
        /// <returns>SystemIcon实体对象</returns>
        public static SystemIcon Single(Expression<Func<SystemIcon, bool>> predicate)
        {
            SystemIcon entity = new SystemIcon();
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        entity = db.BaseDbSet.FirstOrDefault(predicate);
					}
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return entity;
        }

        /// <summary>
        /// 根据主键ID取得单一实体,如果没有找到则返回null
        /// </summary>
        /// <param name="id">实体的主键ID</param>
        /// <returns>SystemIcon实体对象</returns>
        public static SystemIcon Single(int id)
        {
            SystemIcon entity = new SystemIcon();
            if (id > 0)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        entity = db.BaseDbSet.FirstOrDefault(o => o.ID == id);					}
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return entity;
        }

        #endregion

        #region ==========查询数据

        /// <summary>
        /// 获取条数
        /// </summary>
        /// <param name="predicate">表达式</param>
        /// <returns></returns>
        public static int GetCount(Expression<Func<SystemIcon, bool>> predicate)
        {
            int count = 0;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        count = db.BaseDbSet.Where(predicate).Count();
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return count;
        }


		/// <summary>
        /// 获取条数
        /// </summary>
        /// <param name="predicate">表达式</param>
        /// <returns></returns>
        public static int GetCount(ISpecification<SystemIcon> spec)
        {
            int count = 0;
            if (spec != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        count = db.BaseDbSet.Where(spec.Predicate).Count();
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return count;
        }


        /// <summary>
        /// 获取该实体的查询
        /// </summary>
        /// <param name="predicate">表达式</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(Expression<Func<SystemIcon, bool>> predicate)
        {
            return GetQuery(0, predicate, null);
        }

        public static List<SystemIcon> GetQuery(Expression<Func<SystemIcon, bool>> predicate, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            return GetQuery(0, predicate, sortBy, desc);
        }

        /// <summary>
        /// 获取该实体的查询
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="predicate">表达式</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, Expression<Func<SystemIcon, bool>> predicate)
        {
            return GetQuery(top, predicate, null);
        }

        /// <summary>
        /// 获取该实体的查询,单排序
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="predicate">表达式</param>
        /// <param name="sortBy">排序字段</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, Expression<Func<SystemIcon, bool>> predicate, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            List<SystemIcon> list = null;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        IQueryable<SystemIcon> query = db.BaseDbSet.Where(predicate);//默认排序
                        if (top <= 0 && sortBy == null)//直接返回结果，防止不必要的操作
                        {
                            return query.ToList();
                        }
                        IOrderedEnumerable<SystemIcon> queryOrder = null;
                        if (sortBy != null)//执行排序
                        {
                            if (desc)
                            {
                                queryOrder = query.OrderByDescending(sortBy);
                            }
                            else
                            {
                                queryOrder = query.OrderBy(sortBy);
                            }
                        }

                        if (queryOrder != null)
                        {
                            if (top > 0)//top<=0则展示全部
                            {
                                list = queryOrder.Take(top).ToList();
                            }
                            else
                            {
                                list = queryOrder.ToList();
                            }
                        }
                        else
                        {
                            if (top > 0)//top<=0则展示全部
                            {
                                list = query.Take(top).ToList();
                            }
                            else
                            {
                                list = query.ToList();
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return list;
        }

        /// <summary>
        /// 获取该实体的查询,多排序
        /// </summary>
        /// <param name="predicate">表达式</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(Expression<Func<SystemIcon, bool>> predicate, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            return GetQuery(0, predicate, sortDic);
        }

        /// <summary>
        /// 获取该实体的查询,多排序
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="predicate">表达式</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, Expression<Func<SystemIcon, bool>> predicate, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            List<SystemIcon> list = null;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        if (sortDic != null && sortDic.Count > 0)//根据字典内的排序执行
                        {
                            IQueryable<SystemIcon> query = db.BaseDbSet.Where(predicate);
                            IOrderedEnumerable<SystemIcon> queryOrder = null;
                            int num = 0;
                            foreach (KeyValuePair<Func<SystemIcon, object>,bool> kvp in sortDic)
                            {
                                if (num == 0)//第一个
                                {
                                    if (kvp.Value)//True为降序
                                    {
                                        queryOrder = query.OrderByDescending(kvp.Key);
                                    }
                                    else
                                    {
                                        queryOrder = query.OrderBy(kvp.Key);
                                    }
                                }
                                else
                                {
                                    if (kvp.Value)//True为降序
                                    {
                                        queryOrder = queryOrder.ThenByDescending(kvp.Key);
                                    }
                                    else
                                    {
                                        queryOrder = queryOrder.ThenBy(kvp.Key);
                                    }
                                }
                                num++;
                            }
                            if (queryOrder != null)
                            {
                                if (top > 0)//top<=0则展示全部
                                {
                                    list = queryOrder.Take(top).ToList();
                                }
                                else
                                {
                                    list = queryOrder.ToList();
                                }
                            }
                            else
                            {
                                if (top > 0)//top<=0则展示全部
                                {
                                    list = query.Take(top).ToList();
                                }
                                else
                                {
                                    list = query.ToList();
                                }
                            }
                        }
                        else//默认排序 
                        {
                            if (top > 0)//top<=0则展示全部
                            {
                                list = db.BaseDbSet.Where(predicate).Take(top).ToList();
                            }
                            else
                            {
                                list = db.BaseDbSet.Where(predicate).ToList();
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return list;
        }

        /// <summary>
        /// 获取该实体的查询
        /// </summary>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(ISpecification<SystemIcon> specification)
        {
            return GetQuery(0, specification.Predicate);
        }

        /// <summary>
        /// 获取该实体的查询
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, ISpecification<SystemIcon> specification)
        {
            return GetQuery(top, specification.Predicate);
        }

        /// <summary>
        /// 获取该实体的查询,单排序
        /// </summary>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <param name="sortBy">排序字段</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(ISpecification<SystemIcon> specification, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            return GetQuery(0, specification.Predicate, sortBy, desc);
        }

        /// <summary>
        /// 获取该实体的查询,单排序
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <param name="sortBy">排序字段</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, ISpecification<SystemIcon> specification, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            return GetQuery(top, specification.Predicate, sortBy, desc);
        }

        /// <summary>
        /// 获取该实体的查询,多排序
        /// </summary>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(ISpecification<SystemIcon> specification, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            return GetQuery(0, specification.Predicate, sortDic);
        }

        /// <summary>
        /// 获取该实体的查询,多排序
        /// </summary>
        /// <param name="top">查询前几条，top小于等于0则展示全部</param>
        /// <param name="specification">满足表达式规范的组合</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetQuery(int top, ISpecification<SystemIcon> specification, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            return GetQuery(top, specification.Predicate, sortDic);
        }

        #endregion

        #region ==========分页查询数据

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="predicate">Linq表达式[条件查询]</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(Expression<Func<SystemIcon, bool>> predicate, int pageIndex, int pageSize)
        {
            return GetPaged(predicate, pageIndex, pageSize, null);
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="predicate">Linq表达式[条件查询]</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="sortBy">Linq表达式[排序字段]</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(Expression<Func<SystemIcon, bool>> predicate, int pageIndex, int pageSize, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            List<SystemIcon> list = null;
            int totalCount = 0;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        IQueryable<SystemIcon> query = db.BaseDbSet.Where(predicate);//默认排序
                        if (sortBy != null)//执行排序
                        {
                            if (desc)
                            {
                                list = query.OrderByDescending(sortBy).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                            }
                            else
                            {
                                list = query.OrderBy(sortBy).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                            }
                        }
                        else//系统默认排序
                        {
                            list = query.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                        }
                        totalCount = query.Count();
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return list;
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="predicate">Linq表达式[条件查询]</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(Expression<Func<SystemIcon, bool>> predicate, int pageIndex, int pageSize, out int totalCount)
        {
            return GetPaged(predicate, pageIndex, pageSize, out totalCount, null);
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="predicate">Linq表达式[条件查询]</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <param name="sortBy">Linq表达式[排序字段]</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(Expression<Func<SystemIcon, bool>> predicate, int pageIndex, int pageSize, out int totalCount, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            List<SystemIcon> list = null;
            totalCount = 0;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        IQueryable<SystemIcon> query = db.BaseDbSet.Where(predicate);//默认排序
                        if (sortBy != null)//执行排序
                        {
                            if (desc)
                            {
                                list = query.OrderByDescending(sortBy).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                            }
                            else
                            {
                                list = query.OrderBy(sortBy).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                            }
                        }
                        else//系统默认排序
                        {
                            list = query.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                        }
                        totalCount = query.Count();
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return list;
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="specification">满足Linq表达式规范的组合</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(ISpecification<SystemIcon> specification, int pageIndex, int pageSize)
        {
            return GetPaged(specification.Predicate, pageIndex, pageSize, null);
        }
        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="specification">满足Linq表达式规范的组合</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="sortBy">Linq表达式[排序字段]</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(ISpecification<SystemIcon> specification, int pageIndex, int pageSize, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            return GetPaged(specification.Predicate, pageIndex, pageSize, sortBy, desc);
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="specification">满足Linq表达式规范的组合</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(ISpecification<SystemIcon> specification, int pageIndex, int pageSize, out int totalCount)
        {
            return GetPaged(specification.Predicate, pageIndex, pageSize, out totalCount, null);
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="specification">满足Linq表达式规范的组合</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <param name="sortBy">Linq表达式[排序字段]</param>
        /// <param name="desc">默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(ISpecification<SystemIcon> specification, int pageIndex, int pageSize, out int totalCount, Func<SystemIcon, object> sortBy, bool desc = true)
        {
            return GetPaged(specification.Predicate, pageIndex, pageSize, out totalCount, sortBy, desc);
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="predicate">Linq表达式[条件查询]</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>db.BaseDbSet
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(Expression<Func<SystemIcon, bool>> predicate, int pageIndex, int pageSize, out int totalCount, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            List<SystemIcon> list = null;
            totalCount = 0;
            if (predicate != null)
            {
                try
                {
                    using (BaseEntityDbContext<SystemIcon> db = new BaseEntityDbContext<SystemIcon>())
                    {
                        IQueryable<SystemIcon> query = db.BaseDbSet.Where(predicate);
                        IOrderedEnumerable<SystemIcon> queryOrder = null;
                        int num = 0;
                        foreach (KeyValuePair<Func<SystemIcon, object>,bool> kvp in sortDic)
                        {
                            if (num == 0)//第一个
                            {
                                if (kvp.Value)//True为降序
                                {
                                    queryOrder = query.OrderByDescending(kvp.Key);
                                }
                                else
                                {
                                    queryOrder = query.OrderBy(kvp.Key);
                                }
                            }
                            else
                            {
                                if (kvp.Value)//True为降序
                                {
                                    queryOrder = queryOrder.ThenByDescending(kvp.Key);
                                }
                                else
                                {
                                    queryOrder = queryOrder.ThenBy(kvp.Key);
                                }
                            }
                            num++;
                        }
                        if (queryOrder != null)
                        {
                            list = queryOrder.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                        }
                        else//系统默认排序
                        {
                            list = query.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
                        }
                        totalCount = query.Count();
                    }
                }
                catch (Exception ex)
                {
                    log.Error("获取失败", ex);
                }
            }
            return list;
        }

        /// <summary>
        /// 获取分页数据,返回泛型实体List集合
        /// </summary>
        /// <param name="specification">满足Linq表达式规范的组合</param>
        /// <param name="pageIndex">当前索引的页面</param>
        /// <param name="pageSize">每一页，页面的行数.</param>
        /// <param name="totalCount">Out 返回数据总条数</param>
        /// <param name="sortDic">字典存放多个排序字段，Key = 默认True为降序,False升序</param>
        /// <returns>SystemIcon实体对象的List集合</returns>
        public static List<SystemIcon> GetPaged(ISpecification<SystemIcon> specification, int pageIndex, int pageSize, out int totalCount, Dictionary<Func<SystemIcon, object>,bool> sortDic)
        {
            return GetPaged(specification.Predicate, pageIndex, pageSize, out totalCount, sortDic);
        }

        #endregion

        
	}
}

