//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-04-13 17:56:51 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("AreaCode")]
    public class AreaCode : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private string _name = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Name { get{return _name;} set{_name=value;} }
	    private string _code = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Code { get{return _code;} set{_code=value;} }
	    private int _baseid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int BaseId { get{return _baseid;} set{_baseid=value;} }
	    private int _sort = 0;
		/// <summary>
        /// 排序
        /// </summary>
        		[DataMember(Order = 0)]
		public int Sort { get{return _sort;} set{_sort=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "AreaCode";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,Name,Code,BaseId,Sort";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Name = "Name";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Code = "Code";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string BaseId = "BaseId";
            
            /// <summary>
            /// 排序
            /// </summary>
            public readonly static string Sort = "Sort";
            
        }
        #endregion
    }
}

