//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-16 21:24:16 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("BankQuota")]
    public class BankQuota : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _bankid = 0;
		/// <summary>
        /// 银行ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int BankId { get{return _bankid;} set{_bankid=value;} }
	    private decimal _singlequota = 0M;
		/// <summary>
        /// 单笔限额
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal SingleQuota { get{return _singlequota;} set{_singlequota=value;} }
	    private decimal _dayquota = 0M;
		/// <summary>
        /// 每日限额
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal DayQuota { get{return _dayquota;} set{_dayquota=value;} }
	    private decimal _mouthquota = 0M;
		/// <summary>
        /// 每月限额
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal MouthQuota { get{return _mouthquota;} set{_mouthquota=value;} }
	    private string _source = string.Empty;
		/// <summary>
        /// 来源
        /// </summary>
        		[DataMember(Order = 0)]
		public string Source { get{return _source;} set{_source=value;} }
	    private int _channeltype = 0;
		/// <summary>
        /// 渠道
        /// </summary>
        		[DataMember(Order = 0)]
		public int ChannelType { get{return _channeltype;} set{_channeltype=value;} }
	    private int _state = 0;
		/// <summary>
        /// 可用状态 0可用 -1 不可用
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 创建时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 更新时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "BankQuota";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,BankId,SingleQuota,DayQuota,MouthQuota,Source,ChannelType,State,CTime,UTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 银行ID
            /// </summary>
            public readonly static string BankId = "BankId";
            
            /// <summary>
            /// 单笔限额
            /// </summary>
            public readonly static string SingleQuota = "SingleQuota";
            
            /// <summary>
            /// 每日限额
            /// </summary>
            public readonly static string DayQuota = "DayQuota";
            
            /// <summary>
            /// 每月限额
            /// </summary>
            public readonly static string MouthQuota = "MouthQuota";
            
            /// <summary>
            /// 来源
            /// </summary>
            public readonly static string Source = "Source";
            
            /// <summary>
            /// 渠道
            /// </summary>
            public readonly static string ChannelType = "ChannelType";
            
            /// <summary>
            /// 可用状态 0可用 -1 不可用
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 更新时间
            /// </summary>
            public readonly static string UTime = "UTime";
            
        }
        #endregion
    }
}

