//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-08-14 11:29:08 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("Banner")]
    public class Banner : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private string _title = string.Empty;
		/// <summary>
        /// 标题
        /// </summary>
        		[DataMember(Order = 0)]
		public string Title { get{return _title;} set{_title=value;} }
	    private string _wapurl = string.Empty;
		/// <summary>
        /// wap地址
        /// </summary>
        		[DataMember(Order = 0)]
		public string WapURL { get{return _wapurl;} set{_wapurl=value;} }
	    private string _imgurl = string.Empty;
		/// <summary>
        /// 图片地址
        /// </summary>
        		[DataMember(Order = 0)]
		public string ImgUrl { get{return _imgurl;} set{_imgurl=value;} }
	    private int _state = 0;
		/// <summary>
        /// 状态 0 未上线  1 上线
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private DateTime _starttime = DateTime.Now;
		/// <summary>
        /// 开始时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime StartTime { get{return _starttime;} set{_starttime=value;} }
	    private DateTime _endtime = DateTime.Now;
		/// <summary>
        /// 结束时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime EndTime { get{return _endtime;} set{_endtime=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 创建时间 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private int _sort = 0;
		/// <summary>
        /// 排序
        /// </summary>
        		[DataMember(Order = 0)]
		public int Sort { get{return _sort;} set{_sort=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "Banner";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,Title,WapURL,ImgUrl,State,StartTime,EndTime,CTime,Sort";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 标题
            /// </summary>
            public readonly static string Title = "Title";
            
            /// <summary>
            /// wap地址
            /// </summary>
            public readonly static string WapURL = "WapURL";
            
            /// <summary>
            /// 图片地址
            /// </summary>
            public readonly static string ImgUrl = "ImgUrl";
            
            /// <summary>
            /// 状态 0 未上线  1 上线
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 开始时间
            /// </summary>
            public readonly static string StartTime = "StartTime";
            
            /// <summary>
            /// 结束时间
            /// </summary>
            public readonly static string EndTime = "EndTime";
            
            /// <summary>
            /// 创建时间 
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 排序
            /// </summary>
            public readonly static string Sort = "Sort";
            
        }
        #endregion
    }
}

