//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-08-14 11:29:09 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("DebarBankChannel")]
    public class DebarBankChannel : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _bankid = 0;
		/// <summary>
        /// 卡记录ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int BankID { get{return _bankid;} set{_bankid=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private int _channelid = 0;
		/// <summary>
        /// 通道ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int ChannelID { get{return _channelid;} set{_channelid=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "DebarBankChannel";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,BankID,UserId,ChannelID,CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 卡记录ID
            /// </summary>
            public readonly static string BankID = "BankID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 通道ID
            /// </summary>
            public readonly static string ChannelID = "ChannelID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string CTime = "CTime";
            
        }
        #endregion
    }
}

