//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-16 21:24:16 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("TimedTask")]
    public class TimedTask : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _typeid = 0;
		/// <summary>
        /// 任务类型
        /// </summary>
        		[DataMember(Order = 0)]
		public int TypeId { get{return _typeid;} set{_typeid=value;} }
	    private string _value = string.Empty;
		/// <summary>
        /// json参数
        /// </summary>
        		[DataMember(Order = 0)]
		public string Value { get{return _value;} set{_value=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 任务创建时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _exectime = DateTime.Now;
		/// <summary>
        /// 执行时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime ExecTime { get{return _exectime;} set{_exectime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 修改时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private int _state = 0;
		/// <summary>
        /// 任务状态 0等待执行 1已执行
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "TimedTask";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,TypeId,Value,CTime,ExecTime,UTime,State";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 任务类型
            /// </summary>
            public readonly static string TypeId = "TypeId";
            
            /// <summary>
            /// json参数
            /// </summary>
            public readonly static string Value = "Value";
            
            /// <summary>
            /// 任务创建时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 执行时间
            /// </summary>
            public readonly static string ExecTime = "ExecTime";
            
            /// <summary>
            /// 修改时间
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 任务状态 0等待执行 1已执行
            /// </summary>
            public readonly static string State = "State";
            
        }
        #endregion
    }
}

