//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-04-23 13:46:40 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("UserBankCard")]
    public class UserBankCard : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 用户ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private string _bankcode = string.Empty;
		/// <summary>
        /// 银行编码
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankCode { get{return _bankcode;} set{_bankcode=value;} }
	    private string _bankname = string.Empty;
		/// <summary>
        /// 银行名称
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankName { get{return _bankname;} set{_bankname=value;} }
	    private string _bankcard = string.Empty;
		/// <summary>
        /// 银行卡号
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankCard { get{return _bankcard;} set{_bankcard=value;} }
	    private string _mobile = string.Empty;
		/// <summary>
        /// 预留手机号
        /// </summary>
        		[DataMember(Order = 0)]
		public string Mobile { get{return _mobile;} set{_mobile=value;} }
	    private int _typeid = 0;
		/// <summary>
        /// 类型 0 结算卡  1支付卡
        /// </summary>
        		[DataMember(Order = 0)]
		public int TypeId { get{return _typeid;} set{_typeid=value;} }
	    private int _state = 0;
		/// <summary>
        /// 状态 0发起  1绑定成功 -1解绑
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private string _cvn2 = string.Empty;
		/// <summary>
        /// CVN2
        /// </summary>
        		[DataMember(Order = 0)]
		public string CVN2 { get{return _cvn2;} set{_cvn2=value;} }
	    private string _expiresyear = string.Empty;
		/// <summary>
        /// 有效期年
        /// </summary>
        		[DataMember(Order = 0)]
		public string ExpiresYear { get{return _expiresyear;} set{_expiresyear=value;} }
	    private string _expiresmouth = string.Empty;
		/// <summary>
        /// 有效期月
        /// </summary>
        		[DataMember(Order = 0)]
		public string ExpiresMouth { get{return _expiresmouth;} set{_expiresmouth=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// IP
        /// </summary>
        		[DataMember(Order = 0)]
		public string IP { get{return _ip;} set{_ip=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int Platform { get{return _platform;} set{_platform=value;} }
	    private string _relationid = string.Empty;
		/// <summary>
        /// 相关数据
        /// </summary>
        		[DataMember(Order = 0)]
		public string RelationId { get{return _relationid;} set{_relationid=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 创建时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private string _openingbank = string.Empty;
		/// <summary>
        /// 开户行
        /// </summary>
        		[DataMember(Order = 0)]
		public string OpeningBank { get{return _openingbank;} set{_openingbank=value;} }
	    private string _openingserialbank = string.Empty;
		/// <summary>
        /// 开户行联行号
        /// </summary>
        		[DataMember(Order = 0)]
		public string OpeningSerialBank { get{return _openingserialbank;} set{_openingserialbank=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "UserBankCard";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,UserId,BankCode,BankName,BankCard,Mobile,TypeId,State,CVN2,ExpiresYear,ExpiresMouth,IP,Platform,RelationId,CTime,UTime,OpeningBank,OpeningSerialBank";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 用户ID
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 银行编码
            /// </summary>
            public readonly static string BankCode = "BankCode";
            
            /// <summary>
            /// 银行名称
            /// </summary>
            public readonly static string BankName = "BankName";
            
            /// <summary>
            /// 银行卡号
            /// </summary>
            public readonly static string BankCard = "BankCard";
            
            /// <summary>
            /// 预留手机号
            /// </summary>
            public readonly static string Mobile = "Mobile";
            
            /// <summary>
            /// 类型 0 结算卡  1支付卡
            /// </summary>
            public readonly static string TypeId = "TypeId";
            
            /// <summary>
            /// 状态 0发起  1绑定成功 -1解绑
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// CVN2
            /// </summary>
            public readonly static string CVN2 = "CVN2";
            
            /// <summary>
            /// 有效期年
            /// </summary>
            public readonly static string ExpiresYear = "ExpiresYear";
            
            /// <summary>
            /// 有效期月
            /// </summary>
            public readonly static string ExpiresMouth = "ExpiresMouth";
            
            /// <summary>
            /// IP
            /// </summary>
            public readonly static string IP = "IP";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Platform = "Platform";
            
            /// <summary>
            /// 相关数据
            /// </summary>
            public readonly static string RelationId = "RelationId";
            
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 开户行
            /// </summary>
            public readonly static string OpeningBank = "OpeningBank";
            
            /// <summary>
            /// 开户行联行号
            /// </summary>
            public readonly static string OpeningSerialBank = "OpeningSerialBank";
            
        }
        #endregion
    }
}

