//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-04-13 17:56:52 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("Users")]
    public class Users : BaseEntity
    {
        #region Entity Field
        private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private string _username = string.Empty;
		/// <summary>
        /// 用户名
        /// </summary>
        		[DataMember(Order = 0)]
		public string UserName { get{return _username;} set{_username=value;} }
	    private string _password = string.Empty;
		/// <summary>
        /// 密码
        /// </summary>
        		[DataMember(Order = 0)]
		public string Password { get{return _password;} set{_password=value;} }
	    private string _mobile = string.Empty;
		/// <summary>
        /// 手机号
        /// </summary>
        		[DataMember(Order = 0)]
		public string Mobile { get{return _mobile;} set{_mobile=value;} }
	    private string _email = string.Empty;
		/// <summary>
        /// 邮箱
        /// </summary>
        		[DataMember(Order = 0)]
		public string Email { get{return _email;} set{_email=value;} }
	    private string _realname = string.Empty;
		/// <summary>
        /// 真实姓名
        /// </summary>
        		[DataMember(Order = 0)]
		public string RealName { get{return _realname;} set{_realname=value;} }
	    private string _idcard = string.Empty;
		/// <summary>
        /// 身份证号
        /// </summary>
        		[DataMember(Order = 0)]
		public string IdCard { get{return _idcard;} set{_idcard=value;} }
	    private int _isrealstate = 0;
		/// <summary>
        /// 是否实名认证  0未认证  1认证成功
        /// </summary>
        		[DataMember(Order = 0)]
		public int IsRealState { get{return _isrealstate;} set{_isrealstate=value;} }
	    private DateTime _realtime = DateTime.Now;
		/// <summary>
        /// 认证时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime RealTime { get{return _realtime;} set{_realtime=value;} }
	    private int _viptype = 0;
		/// <summary>
        /// Vip等级 
        /// </summary>
        		[DataMember(Order = 0)]
		public int VipType { get{return _viptype;} set{_viptype=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// 注册IP地址
        /// </summary>
        		[DataMember(Order = 0)]
		public string IP { get{return _ip;} set{_ip=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 注册平台
        /// </summary>
        		[DataMember(Order = 0)]
		public int PlatForm { get{return _platform;} set{_platform=value;} }
	    private string _soure = string.Empty;
		/// <summary>
        /// 推广来源
        /// </summary>
        		[DataMember(Order = 0)]
		public string Soure { get{return _soure;} set{_soure=value;} }
	    private int _state = 0;
		/// <summary>
        /// 用户状态 0正常  -1 锁定
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 注册时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 用户信息更新时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private int _baseuserid = 0;
		/// <summary>
        /// 邀请人ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int BaseUserId { get{return _baseuserid;} set{_baseuserid=value;} }
	    private int _bankcardphoto = 0;
		/// <summary>
        /// 银行卡正面照
        /// </summary>
        		[DataMember(Order = 0)]
		public int BankCardPhoto { get{return _bankcardphoto;} set{_bankcardphoto=value;} }
	    private int _idcardphoto = 0;
		/// <summary>
        /// 身份证正面照
        /// </summary>
        		[DataMember(Order = 0)]
		public int IdCardPhoto { get{return _idcardphoto;} set{_idcardphoto=value;} }
	    private int _idcardbackphoto = 0;
		/// <summary>
        /// 身份证背面照
        /// </summary>
        		[DataMember(Order = 0)]
		public int IdCardBackPhoto { get{return _idcardbackphoto;} set{_idcardbackphoto=value;} }
	    private int _personphoto = 0;
		/// <summary>
        /// 身份证 +银行卡+本人合照
        /// </summary>
        		[DataMember(Order = 0)]
		public int PersonPhoto { get{return _personphoto;} set{_personphoto=value;} }
	    private int _avatarimg = 0;
		/// <summary>
        /// 头像照片
        /// </summary>
        		[DataMember(Order = 0)]
		public int AvatarImg { get{return _avatarimg;} set{_avatarimg=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "Users";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "UserId,UserName,Password,Mobile,Email,RealName,IdCard,IsRealState,RealTime,VipType,IP,PlatForm,Soure,State,CTime,UTime,BaseUserId,BankCardPhoto,IdCardPhoto,IdCardBackPhoto,PersonPhoto,AvatarImg";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 用户名
            /// </summary>
            public readonly static string UserName = "UserName";
            
            /// <summary>
            /// 密码
            /// </summary>
            public readonly static string Password = "Password";
            
            /// <summary>
            /// 手机号
            /// </summary>
            public readonly static string Mobile = "Mobile";
            
            /// <summary>
            /// 邮箱
            /// </summary>
            public readonly static string Email = "Email";
            
            /// <summary>
            /// 真实姓名
            /// </summary>
            public readonly static string RealName = "RealName";
            
            /// <summary>
            /// 身份证号
            /// </summary>
            public readonly static string IdCard = "IdCard";
            
            /// <summary>
            /// 是否实名认证  0未认证  1认证成功
            /// </summary>
            public readonly static string IsRealState = "IsRealState";
            
            /// <summary>
            /// 认证时间
            /// </summary>
            public readonly static string RealTime = "RealTime";
            
            /// <summary>
            /// Vip等级 
            /// </summary>
            public readonly static string VipType = "VipType";
            
            /// <summary>
            /// 注册IP地址
            /// </summary>
            public readonly static string IP = "IP";
            
            /// <summary>
            /// 注册平台
            /// </summary>
            public readonly static string PlatForm = "PlatForm";
            
            /// <summary>
            /// 推广来源
            /// </summary>
            public readonly static string Soure = "Soure";
            
            /// <summary>
            /// 用户状态 0正常  -1 锁定
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 注册时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 用户信息更新时间
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 邀请人ID
            /// </summary>
            public readonly static string BaseUserId = "BaseUserId";
            
            /// <summary>
            /// 银行卡正面照
            /// </summary>
            public readonly static string BankCardPhoto = "BankCardPhoto";
            
            /// <summary>
            /// 身份证正面照
            /// </summary>
            public readonly static string IdCardPhoto = "IdCardPhoto";
            
            /// <summary>
            /// 身份证背面照
            /// </summary>
            public readonly static string IdCardBackPhoto = "IdCardBackPhoto";
            
            /// <summary>
            /// 身份证 +银行卡+本人合照
            /// </summary>
            public readonly static string PersonPhoto = "PersonPhoto";
            
            /// <summary>
            /// 头像照片
            /// </summary>
            public readonly static string AvatarImg = "AvatarImg";
            
        }
        #endregion
    }
}

