//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-09 21:41:15 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("UserImage")]
    public class UserImage : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private string _url = string.Empty;
		/// <summary>
        /// 图片地址
        /// </summary>
        		[DataMember(Order = 0)]
		public string Url { get{return _url;} set{_url=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 用户ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private int _state = 0;
		/// <summary>
        /// 状态 0新上传 1使用中 -1 已删除
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 上传时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Ip { get{return _ip;} set{_ip=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 来源
        /// </summary>
        		[DataMember(Order = 0)]
		public int PlatForm { get{return _platform;} set{_platform=value;} }
	    private string _filename = string.Empty;
		/// <summary>
        /// 文件名
        /// </summary>
        		[DataMember(Order = 0)]
		public string FileName { get{return _filename;} set{_filename=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "UserImage";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,Url,UserId,State,CTime,UTime,Ip,PlatForm,FileName";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 图片地址
            /// </summary>
            public readonly static string Url = "Url";
            
            /// <summary>
            /// 用户ID
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 状态 0新上传 1使用中 -1 已删除
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 上传时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Ip = "Ip";
            
            /// <summary>
            /// 来源
            /// </summary>
            public readonly static string PlatForm = "PlatForm";
            
            /// <summary>
            /// 文件名
            /// </summary>
            public readonly static string FileName = "FileName";
            
        }
        #endregion
    }
}

