//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-16 21:24:16 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("UserShare")]
    public class UserShare : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 创建时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private string _shareurl = string.Empty;
		/// <summary>
        /// 分享URL
        /// </summary>
        		[DataMember(Order = 0)]
		public string ShareUrl { get{return _shareurl;} set{_shareurl=value;} }
	    private string _title = string.Empty;
		/// <summary>
        /// 标题
        /// </summary>
        		[DataMember(Order = 0)]
		public string Title { get{return _title;} set{_title=value;} }
	    private string _imageurl = string.Empty;
		/// <summary>
        /// 缩略图URL
        /// </summary>
        		[DataMember(Order = 0)]
		public string ImageUrl { get{return _imageurl;} set{_imageurl=value;} }
	    private string _context = string.Empty;
		/// <summary>
        /// 内容
        /// </summary>
        		[DataMember(Order = 0)]
		public string Context { get{return _context;} set{_context=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 平台
        /// </summary>
        		[DataMember(Order = 0)]
		public int Platform { get{return _platform;} set{_platform=value;} }
	    private int _soure = 0;
		/// <summary>
        /// 分享平台
        /// </summary>
        		[DataMember(Order = 0)]
		public int Soure { get{return _soure;} set{_soure=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// IP
        /// </summary>
        		[DataMember(Order = 0)]
		public string Ip { get{return _ip;} set{_ip=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "UserShare";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,UserId,CTime,ShareUrl,Title,ImageUrl,Context,Platform,Soure,Ip";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 分享URL
            /// </summary>
            public readonly static string ShareUrl = "ShareUrl";
            
            /// <summary>
            /// 标题
            /// </summary>
            public readonly static string Title = "Title";
            
            /// <summary>
            /// 缩略图URL
            /// </summary>
            public readonly static string ImageUrl = "ImageUrl";
            
            /// <summary>
            /// 内容
            /// </summary>
            public readonly static string Context = "Context";
            
            /// <summary>
            /// 平台
            /// </summary>
            public readonly static string Platform = "Platform";
            
            /// <summary>
            /// 分享平台
            /// </summary>
            public readonly static string Soure = "Soure";
            
            /// <summary>
            /// IP
            /// </summary>
            public readonly static string Ip = "Ip";
            
        }
        #endregion
    }
}

