//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-09 21:41:15 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("View_PayRecord")]
    public class ViewPayRecord : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private int _requestid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int RequestId { get{return _requestid;} set{_requestid=value;} }
	    private string _code = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Code { get{return _code;} set{_code=value;} }
	    private decimal _amount = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Amount { get{return _amount;} set{_amount=value;} }
	    private decimal _withdrawamount = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal WithDrawAmount { get{return _withdrawamount;} set{_withdrawamount=value;} }
	    private decimal _actualamount = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal ActualAmount { get{return _actualamount;} set{_actualamount=value;} }
	    private decimal _fee = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Fee { get{return _fee;} set{_fee=value;} }
	    private decimal _fee3 = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Fee3 { get{return _fee3;} set{_fee3=value;} }
	    private decimal _rate = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Rate { get{return _rate;} set{_rate=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private string _realname = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string RealName { get{return _realname;} set{_realname=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Ip { get{return _ip;} set{_ip=value;} }
	    private DateTime _handletime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime HandleTime { get{return _handletime;} set{_handletime=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int Platform { get{return _platform;} set{_platform=value;} }
	    private string _mobile = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Mobile { get{return _mobile;} set{_mobile=value;} }
	    private string _bankcard = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankCard { get{return _bankcard;} set{_bankcard=value;} }
	    private string _bankcode = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankCode { get{return _bankcode;} set{_bankcode=value;} }
	    private string _payerphone = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string PayerPhone { get{return _payerphone;} set{_payerphone=value;} }
	    private int _channeltype = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int ChannelType { get{return _channeltype;} set{_channeltype=value;} }
	    private string _bankname = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string BankName { get{return _bankname;} set{_bankname=value;} }
	    private int _state = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private decimal _income = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Income { get{return _income;} set{_income=value;} }
	    private decimal _drawincome = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal DrawIncome { get{return _drawincome;} set{_drawincome=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "View_PayRecord";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,UserId,RequestId,Code,Amount,WithDrawAmount,ActualAmount,Fee,Fee3,Rate,CTime,RealName,Ip,HandleTime,Platform,Mobile,BankCard,BankCode,PayerPhone,ChannelType,BankName,State,Income,DrawIncome";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string RequestId = "RequestId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Code = "Code";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Amount = "Amount";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string WithDrawAmount = "WithDrawAmount";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ActualAmount = "ActualAmount";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Fee = "Fee";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Fee3 = "Fee3";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Rate = "Rate";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string RealName = "RealName";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Ip = "Ip";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string HandleTime = "HandleTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Platform = "Platform";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Mobile = "Mobile";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string BankCard = "BankCard";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string BankCode = "BankCode";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string PayerPhone = "PayerPhone";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ChannelType = "ChannelType";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string BankName = "BankName";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Income = "Income";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string DrawIncome = "DrawIncome";
            
        }
        #endregion
    }
}

