//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-08-14 11:29:12 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("WithDraw")]
    public class WithDraw : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private int _platform = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int Platform { get{return _platform;} set{_platform=value;} }
	    private decimal _amount = 0M;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Amount { get{return _amount;} set{_amount=value;} }
	    private int _payid = 0;
		/// <summary>
        /// 收款订单ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int PayId { get{return _payid;} set{_payid=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string IP { get{return _ip;} set{_ip=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private int _transferway = 0;
		/// <summary>
        /// 结算方式  1:T0  自助结算  2: T1自助结算
        /// </summary>
        		[DataMember(Order = 0)]
		public int TransferWay { get{return _transferway;} set{_transferway=value;} }
	    private int _state = 0;
		/// <summary>
        /// 0发起中 1 已接受   2处理中 10 打款成功  -1 打款失败  -2 已退款  -3已撤销 -4失败
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private DateTime _handletime = DateTime.Now;
		/// <summary>
        /// 处理时间
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime HandleTime { get{return _handletime;} set{_handletime=value;} }
	    private string _receiver = string.Empty;
		/// <summary>
        /// 收款人
        /// </summary>
        		[DataMember(Order = 0)]
		public string Receiver { get{return _receiver;} set{_receiver=value;} }
	    private string _receiverbankcardno = string.Empty;
		/// <summary>
        /// 收款卡号
        /// </summary>
        		[DataMember(Order = 0)]
		public string ReceiverBankCardNo { get{return _receiverbankcardno;} set{_receiverbankcardno=value;} }
	    private string _receiverbank = string.Empty;
		/// <summary>
        /// 收款银行
        /// </summary>
        		[DataMember(Order = 0)]
		public string ReceiverBank { get{return _receiverbank;} set{_receiverbank=value;} }
	    private decimal _fee = 0M;
		/// <summary>
        /// 手续费
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal Fee { get{return _fee;} set{_fee=value;} }
	    private decimal _basicfee = 0M;
		/// <summary>
        /// 基本手续费
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal BasicFee { get{return _basicfee;} set{_basicfee=value;} }
	    private decimal _extargetfee = 0M;
		/// <summary>
        /// 额外手续费
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal ExTargetFee { get{return _extargetfee;} set{_extargetfee=value;} }
	    private decimal _actualamount = 0M;
		/// <summary>
        /// 结算实际到账金额
        /// </summary>
        		[DataMember(Order = 0)]
		public decimal ActualAmount { get{return _actualamount;} set{_actualamount=value;} }
	    private string _message = string.Empty;
		/// <summary>
        /// 结算失败的原因
        /// </summary>
        		[DataMember(Order = 0)]
		public string Message { get{return _message;} set{_message=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "WithDraw";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,UserId,Platform,Amount,PayId,IP,CTime,UTime,TransferWay,State,HandleTime,Receiver,ReceiverBankCardNo,ReceiverBank,Fee,BasicFee,ExTargetFee,ActualAmount,Message";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Platform = "Platform";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Amount = "Amount";
            
            /// <summary>
            /// 收款订单ID
            /// </summary>
            public readonly static string PayId = "PayId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string IP = "IP";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 结算方式  1:T0  自助结算  2: T1自助结算
            /// </summary>
            public readonly static string TransferWay = "TransferWay";
            
            /// <summary>
            /// 0发起中 1 已接受   2处理中 10 打款成功  -1 打款失败  -2 已退款  -3已撤销 -4失败
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 处理时间
            /// </summary>
            public readonly static string HandleTime = "HandleTime";
            
            /// <summary>
            /// 收款人
            /// </summary>
            public readonly static string Receiver = "Receiver";
            
            /// <summary>
            /// 收款卡号
            /// </summary>
            public readonly static string ReceiverBankCardNo = "ReceiverBankCardNo";
            
            /// <summary>
            /// 收款银行
            /// </summary>
            public readonly static string ReceiverBank = "ReceiverBank";
            
            /// <summary>
            /// 手续费
            /// </summary>
            public readonly static string Fee = "Fee";
            
            /// <summary>
            /// 基本手续费
            /// </summary>
            public readonly static string BasicFee = "BasicFee";
            
            /// <summary>
            /// 额外手续费
            /// </summary>
            public readonly static string ExTargetFee = "ExTargetFee";
            
            /// <summary>
            /// 结算实际到账金额
            /// </summary>
            public readonly static string ActualAmount = "ActualAmount";
            
            /// <summary>
            /// 结算失败的原因
            /// </summary>
            public readonly static string Message = "Message";
            
        }
        #endregion
    }
}

