//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的...
//    生成时间 2018-05-09 21:41:15 By CClump
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ITOrm.Core.Dapper;
using System.Runtime.Serialization;
namespace ITOrm.Host.Models
{
    /// <summary>
    /// 备注
    /// </summary>
    [Serializable]
	[Table("YeepayLog")]
    public class YeepayLog : BaseEntity
    {
        #region Entity Field
        private int _id = 0;
		/// <summary>
        /// 
        /// </summary>
        [Key]		[DataMember(Order = 0)]
		public int ID { get{return _id;} set{_id=value;} }
	    private int _userid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int UserId { get{return _userid;} set{_userid=value;} }
	    private int _typeid = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int TypeId { get{return _typeid;} set{_typeid=value;} }
	    private int _keyid = 0;
		/// <summary>
        /// 关联ID
        /// </summary>
        		[DataMember(Order = 0)]
		public int KeyId { get{return _keyid;} set{_keyid=value;} }
	    private DateTime _ctime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime CTime { get{return _ctime;} set{_ctime=value;} }
	    private DateTime _utime = DateTime.Now;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public DateTime UTime { get{return _utime;} set{_utime=value;} }
	    private int _platfrom = 0;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public int Platfrom { get{return _platfrom;} set{_platfrom=value;} }
	    private string _ip = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string IP { get{return _ip;} set{_ip=value;} }
	    private string _code = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Code { get{return _code;} set{_code=value;} }
	    private string _msg = string.Empty;
		/// <summary>
        /// 
        /// </summary>
        		[DataMember(Order = 0)]
		public string Msg { get{return _msg;} set{_msg=value;} }
	    private int _state = 0;
		/// <summary>
        /// 0发起 
        /// </summary>
        		[DataMember(Order = 0)]
		public int State { get{return _state;} set{_state=value;} }
	    private int _channeltype = 0;
		/// <summary>
        /// 渠道 0 易宝 1荣邦科技
        /// </summary>
        		[DataMember(Order = 0)]
		public int ChannelType { get{return _channeltype;} set{_channeltype=value;} }
	    
		#endregion

        #region 字段名信息 方便调用
        /// <summary>
        /// 数据表“WS_Log”的相关信息[数据库名、表名及字段名]
        /// </summary>
        [Serializable]
        public struct _
        {
            /// <summary>
            /// 数据库名
            /// </summary>
            public readonly static string DataBaseName = "SujinDB";

            /// <summary>
            /// 表名
            /// </summary>
            public readonly static string TableName = "YeepayLog";

            /// <summary>
            /// 所有字段
            /// </summary>
            public readonly static string All = "ID,UserId,TypeId,KeyId,CTime,UTime,Platfrom,IP,Code,Msg,State,ChannelType";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string ID = "ID";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UserId = "UserId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string TypeId = "TypeId";
            
            /// <summary>
            /// 关联ID
            /// </summary>
            public readonly static string KeyId = "KeyId";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string CTime = "CTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string UTime = "UTime";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Platfrom = "Platfrom";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string IP = "IP";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Code = "Code";
            
            /// <summary>
            /// 
            /// </summary>
            public readonly static string Msg = "Msg";
            
            /// <summary>
            /// 0发起 
            /// </summary>
            public readonly static string State = "State";
            
            /// <summary>
            /// 渠道 0 易宝 1荣邦科技
            /// </summary>
            public readonly static string ChannelType = "ChannelType";
            
        }
        #endregion
    }
}

